### ISSUE TITLE
Issue with native-compilation

### ISSUE THREAD

**Issue by bbuccianti** [minad/vertico#15] opened 2021-04-13 16:22 UTC
I don't really know why, but when vertico is loaded from a .eln file, it's showing this behaviour.

![Image of explained behaviour](https://p.buccianti.dev/screen.png)

You can note that the prompt isn't there. But when I eval-buffer vertico.el it just works as expected. Any idea what is happening there?

*EDIT by @minad*: The screenshot above does not reflect the bug anymore since @bbuccianti changed the uploaded image. (@bbuccianti note that you can use the gh image upload instead)

**Comment by minad** [comment] 2021-04-13 16:57
No idea, this is the same issue as #13. It is certainly not a Vertico issue if it only happens with native compilation. Do you manage to reproduce it with emacs -Q in the following modes? Please check that you use the newest Emacs 28 version.

* interpreted/eval (does not seem like it from what you wrote about with eval-buffer)
* byte-compiled
* natively compiled

This should be discussed with Emacs upstream if you find a difference in behavior between these three evaluation modes.

@manuel-ubert is using Emacs 28 master (https://github.com/emacs-mirror/emacs/commit/6de79542e4) and he has not observed issues.

**Comment by bbuccianti** [comment] 2021-04-13 18:29
I can confirm that with emacs -Q the issue only happen when running emacs-lisp-native-compile-and-load on vertico.el file. With intepreted and byte-compiled works properly.

**Comment by minad** [comment] 2021-04-13 18:51
Okay, do you use the newest emacs28 gccemacs? I guess Andrea Corrallo `@Koral` is interested if you find cases where gccemacs deviates from bytecompiled Emacs. You may want to create an upstream bug report, but please check the current version first.

**Comment by bbuccianti** [comment] 2021-04-13 20:29
I'm using fb08402a709896bc7ef95e50c7f14df2ea629814 

For now, I just add "vertico" to comp-deferred-compilation-deny-list in order to avoid the native compilation.

Thanks, @minad !

**Comment by manuel-uberti** [comment] 2021-04-14 07:38
Could you still report it to Emacs, please? I'd be good if Andrea or another Emacs maintainer with more knowledge on byte compilation can have a look at this.

**Comment by minad** [comment] 2021-04-14 10:10
CC @Koral

**Comment by manuel-uberti** [comment] 2021-04-14 10:36
I am not sure @AndreaCorallo will get a notification through an edit, so here is my kind ping. Andrea, if you get two notifications blame me, not Daniel. In that case, sorry about the noise.

**Comment by AndreaCorallo** [comment] 2021-04-14 10:37
I would be helpful if one of the vertico developers could investigate a little point out what's the function that is misbehaving.

**Comment by minad** [comment] 2021-04-14 11:43
I am not yet using Emacs28 gccemacs, so I cannot be of much help as of now. Maybe @manuel-uberti or @bbuccianti can help?  I have no idea what causes this. If one assumes that there is some miscompilation I would expect to see errors at other different places.

**Comment by manuel-uberti** [comment] 2021-04-14 11:47
I am not using gccemacs at the moment, although I did try it in the past (i.e., before Vertico) without any problem and I am just waiting for it to be soon on master.

If @bbuccianti doesn't beat me to it, and this is not urgent, as soon as I can build master properly with native-comp I'll see if I can reproduce the problem and hopefully provide more details.

**Comment by minad** [comment] 2021-04-14 11:50
See also https://github.com/minad/consult/issues/274. The issue seems to be related to faces/strings, maybe strings which are mutated with properties. In Consult we saw issues with the following code:

~~~ elisp
         (consult--multi-align (propertize
                                " " ;; NOTE: Single space
                                'display
                                `(space :align-to (+ left ,(cadr candidates)))))
~~~

The odd behavior went away when doing this (cc @tumashu)

~~~ elisp
         (consult--multi-align (propertize
                                (substring-no-properties " ") ;; NOTE substring-no-properties
                                'display
                                `(space :align-to (+ left ,(cadr candidates)))))

         (consult--multi-align (propertize
                                "  " 'display ;; NOTE double space
                                `(space :align-to (+ left ,(cadr candidates)))))
~~~

This is also very odd and when I understood @tumashu correctly, they only observed it on gccemacs (20210330), but maybe that version was too old.

**Comment by bdarcus** [comment] 2021-04-14 12:08
I see the same behavior, but no warnings in messages.

``` elisp
GNU Emacs 28.0.50 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.28, cairo version 1.17.4) of 2021-04-02
```

**Comment by tumashu** [comment] 2021-04-14 12:36
@minad maybe because I edit code then eval-buffer, instead of add substring-no-properties

**Comment by minad** [comment] 2021-04-14 12:57
Ah okay, @tumashu in your case you simply reevaluate the code. You could also evaluate the original code and the error might go away.

**Comment by minad** [comment] 2021-04-14 12:59
@bdarcus Is this emacs master or gccemacs? Please report the exact version, there is the variable `emacs-repository-version`

**Comment by bdarcus** [comment] 2021-04-14 13:16
> @bdarcus Is this emacs master or gccemacs? Please report the exact version, there is the variable `emacs-repository-version`

I am on Fedora (34, beta), and use this copr package:

https://copr.fedorainfracloud.org/coprs/deathwish/emacs-pgtk-nativecomp/

That variable is nil.

**Comment by bbuccianti** [comment] 2021-04-14 15:23
I've tried .eln vertico and the problem it's there. But, after a few tries, seems like after eval only vertico--display-candidates the issue dissapeared. I don't know if that's helpful or not.

**Comment by AndreaCorallo** [comment] 2021-04-14 17:59
I suggest to verify the warnings in the `*Async-native-compile-log*` buffer related to the compilation of vertico.
One can also force the recompilation using `native-compile-async` if the package was compiled in a previous session.

**Comment by minad** [comment] 2021-04-14 18:11
@AndreaCorallo Thank you, that's helpful! Maybe @bbuccianti or @tumashu can post a log?

**Comment by tumashu** [comment] 2021-04-15 00:29
```
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
Compiling ~/.emacs.d/elpa-28/vertico-0.4/vertico.el...
Compilation finished.
Compiling /home/feng/.emacs.d/elpa-28/vertico-0.4/vertico.el...
Compilation finished.

```

**Comment by bbuccianti** [comment] 2021-04-15 18:35
Mine native compilation shows the same as @tumashu 

> Compiling /home/work/.emacs.d/straight/build/vertico/vertico.el...
> Compilation finished.

The issue it's still there. If I can do anything to keep helping debug the problem, please tell me.

**Comment by tsdh** [comment] 2021-04-18 19:04
I've filed an emacs report here: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=47868

**Comment by minad** [comment] 2021-04-21 13:34
Closing here, bug is being worked on https://debbugs.gnu.org/cgi/bugreport.cgi?bug=47868

**Closed by minad** 2021-04-21 13:34 UTC
