### ISSUE TITLE
Key bindings from vertico-map not available in temporary multiform grid view

### ISSUE THREAD

**Issue by oantolin** [minad/vertico#176] opened 2022-01-08 16:31 UTC
Hi @minad! I just learned about `vertico-unobtrusive-mode` and believe that was the final missing piece for me to abandon `embark-collect-completions` for good! (The unobstrusive mode seems to me strictly better than not displaying any completions at all, and indeed, I nearly wrote one myself.)

I'm just having trouble with the key bindings. The docstring for `vertico-grid-map` says _additional_ keymap activated in grid mode, which I take to mean that my bindings in `vertico-map` should still be available. But try this in `emacs -q`

```elisp
(package-initialize)
(vertico-mode)
(vertico-unobtrusive-mode)
(vertico-multiform-mode)
(define-key vertico-map (kbd "M-q") #'vertico-multiform-grid)
```

Now run `find-file`, say. It correctly starts in unobstrusive mode and if you press `C-h c M-q` you get `vertico-multiform-grid`. But now if you press `M-q` it does switch to the grid display but the `M-q` disappears! Now `C-h c M-q` says `fill-paragraph`!

Did I misinterpret the docstring? Am I supposed to repeat my key bindings in `vertico-grid-map`?

**Comment by minad** [comment] 2022-01-08 17:35
Oh that's odd. It works in my config but I can reproduce the issue with emacs -Q. I am doing something bad to vertico-map  in these extensions, see https://github.com/minad/vertico/blob/3895a797ff82075e29799c688142dc6f18ad1cb4/extensions/vertico-grid.el#L156-L164. Maybe you have a better idea? I need some way to robustly and temporarily augment vertico-map with additional keybindings.

**Comment by minad** [comment] 2022-01-08 17:44
I think the issue is that the modes are toggled in the wrong order somehow and the keymap mutations do not commute.

**Comment by oantolin** [comment] 2022-01-08 17:45
That mutation of `vertico-map` in `vertico-grid-mode` looks correct to me. I'm surprised this is happening.

**Comment by oantolin** [comment] 2022-01-08 17:46
> I need some way to robustly and temporarily augment vertico-map with additional keybindings.

Why do you need the mappings to be in `vertico-map`? Why isn't it good enough to just enable `vertico-grid-map` as an additional minor mode map in the normal way for minor modes?

**Comment by minad** [comment] 2022-01-08 17:49
> That mutation of vertico-map in vertico-grid-mode looks correct to me. I'm surprised this is happening.

It is only correct for the correct toggle order. I will use memq and delq to make this more robust.

> Why do you need the mappings to be in vertico-map? Why isn't it good enough to just enable vertico-grid-map as an additional minor mode map in the normal way for minor modes?

I want to activate the map only in the minibuffer and I have already setup vertico-map there, so this seemed like the easiest way to do this. But I went back and forth and tried various methods. This one seemed to be the best one, until you opened the issue :-P

**Comment by minad** [comment] 2022-01-08 17:53
Unfortunately https://github.com/minad/vertico/commit/56642f8ea6c45548b58b71e675c362daead9b1f5 does not fix the issue.

**Comment by minad** [comment] 2022-01-08 17:59
This fixes the issue, such that the keybinding sticks around.

~~~ elisp
(package-initialize)
(vertico-mode)
(define-key vertico-map (kbd "M-q") #'vertico-multiform-grid)
(vertico-unobtrusive-mode)
(vertico-multiform-mode)
~~~

I haven't understood why. It seems that define-key adds the key to the map added by vertico-unobtrusive-mode then instead of to the toplevel map as I had expected.

**Comment by oantolin** [comment] 2022-01-08 17:59
How about adding a new internal variable `vertico--keymaps` that you can modify by `push` and `delq` and whenever you change the variable you also activate the new maps with `(use-local-map (make-composed-keymap vertico--keymaps))`?

**Comment by oantolin** [comment] 2022-01-08 18:01
> I haven't understood why. It seems that define-key adds the key to the map added by vertico-unobtrusive-mode then instead of to the toplevel map as I had expected.

Oh, weird! Maybe `define-key` mutates the first innermost keymap, so that in `(keymap (keymap (keymap ___))` the bindings gets added in `___`?

**Comment by minad** [comment] 2022-01-08 18:01
> Oh, weird! Maybe define-key mutates the first innermost keymap, so that in (keymap (keymap (keymap ___)) the bindings gets added in ___?

Yes, indeed. I would argue that this is a bug. But whatever :shrug:

**Comment by oantolin** [comment] 2022-01-08 18:02
Maybe you don't need to change anything. I can just define the key-bindings first, as you suggested above.

**Comment by oantolin** [comment] 2022-01-08 18:03
But it is potentially confusing, I did come across this naturally, not doing something "weird".

**Comment by minad** [comment] 2022-01-08 18:06
> But it is potentially confusing, I did come across this naturally, not doing something "weird".

It is confusing and I consider this a bug. It should be fixed.

**Comment by minad** [comment] 2022-01-08 18:10
~~~ elisp
(setq map1 (make-sparse-keymap))
(define-key map1 "1" 'one)
(setq map2 (make-sparse-keymap))
(define-key map2 "2" 'two)
(setq pmap (make-sparse-keymap))
(define-key pmap "p" 'parent)

(setq cmap (make-composed-keymap (list map1 map2) pmap))
(define-key cmap "c" 'composed)
~~~

I mean WTF. Why does this mutate map1? Does not seem okay to me.

**Closed** 2022-01-08 20:27 UTC

**Comment by oantolin** [comment] 2022-01-08 23:55
Great, thank you! Seeing you use `minor-mode-map-alist` for this made me wonder if there isn't a way to use Emacs's normal minor mode keymap handling for the vertical extensions. Or does that machinery refuse to work in the minibuffer?

**Comment by minad** [comment] 2022-01-09 00:04
I have to bend the machinery slightly. As you are aware, the `minor-mode-map-alist` keymaps are activated depending on the corresponding variable values. Usually the variable is the minor mode variable. However in this case I want to activate the keymap only in the minibuffer. Therefore I use `vertico--input` as variable. Note that `vertico-grid-mode` etc are global modes, which are toggled temporarily, since they overwrite the display machinery via advices. This design may look a bit obscure and one may expect that these sub-modes are only minibuffer-local but the current design is nicely decoupled. The global mode design works only because minibuffers are recursively nested. You cannot jump from minibuffer 3 to 1 to 2 etc.

The alternative would be to introduce hooks or function variables for all the entry points and then overwrite them buffer locally. It may make sense to explore this at some point, getting rid of all the advices. But this would then imply that vertico.el has to know about all the possible hooking points (of course by now it does, but when I initially made vertico.el that was not so clear).

**Comment by oantolin** [comment] 2022-01-09 05:22
I'm pretty excited about vertico-unobtrusive-mode, now I that I know about it I can finally switch to Vertico!

**Comment by minad** [comment] 2022-01-09 06:15
I must say I was pretty skeptical at first but I am also using unobtrusive now at least for M-x and buffer. For files I went flat, for grep, imenu and outline I use buffer and I keep the vertical display for the rest. I also had the concern that this may feel inconsistent, but the behavior is overall still consistent, even if the display is not the same in every scenario.
