### ISSUE TITLE
Activating vertico on demand

### ISSUE THREAD

**Issue by gcv** [minad/vertico#149] opened 2021-10-31 15:04 UTC
(Apologies if this is addressed in another ticket or in the documentation, but I didn't find anything...)

Is there a way to keep vertico "off" until I hit <kbd>Tab</kbd> (or another key) in the minibuffer? Asking because I'm looking for a way to keep default Emacs minibuffer behavior _except_ for the completion system, which would be replaced with vertico. When Emacs would normally pop up its `*Completions*` buffer, I instead want to see vertico step in. But unless I hit <kbd>Tab</kbd>, the minibuffer would remain just one line in height (or stock), not resized to the candidate count.

It seems like this could be done by messing with `vertico-count` inside some function advice, but before I roll up my sleeves and start hacking away, I was just wondering if there's an easy or built-in way to do it.

Thanks!

**Comment by minad** [comment] 2021-10-31 16:28
Incidentally I just thought about this exact problem a few days ago - in particular inspired by @protesilaos' [mct.el](https://github.com/protesilaos/mct). You can try the tiny vertico-demand extension, which I just wrote and implements the idea: https://github.com/minad/vertico/blob/demand/extensions/vertico-demand.el. I have to play a bit more with it, but it seems to work quite well overall. Before Vertico pops up the UI behaves mostly like default completion. The question is if there is a bit of an impedance mismatch as soon as the Vertico UI pops up, e.g., if completion-cycle-threshold>1. Please give it a try and let me know what you think of it.

**Comment by minad** [comment] 2021-10-31 17:30
I must say - I would need some time to adapt to this model. For some commands it works very well but not for some others like consult-buffer. I understand now why @protesilaos doesn't use consult-buffer, since it gives too many false matches. These false matches don't hurt if the Vertico UI is open, since then the first candidate will be selected automatically. 

@gcv You may want to try mct.el, maybe this UI generally fits you better. I still have to use mct.el a bit more extensively, but I am hold back a bit since I am still on Emacs 27 and Emacs 27 does not yet support the one-column completions buffer format.

**Comment by gcv** [comment] 2021-10-31 21:20
@minad: I see what you're saying about `consult-buffer`, but honestly, the slight breakage there is acceptable from my point of view. (But please see my suggestion about whitelisting functions below, since it'll make the problem less severe.) After a bit of testing, vertico-demand seems to do what I asked for.

A vertico-demand feature I'd like to request: a whitelist of commands which _automatically_ enable vertico display. This list of commands should accept either symbols (representing functions) or regexps to represent families of functions. (Something akin to `mini-frame-ignore-commands` from the miniframe package, but the inverse — a whitelist instead of a blacklist.) You might default that list to `'("consult-.*")`, for example, which bypasses the `consult-buffer` display problem. In my experience, Consult pretty much requires a completion system like Vertico or Selectrum anyway. (And I myself would add `execute-extended-command`.)

Thanks for the quick turnaround on this, by the way!

PS: mct.el is intriguing, but I'm also on Emacs 27. 

PPS: I just found discussion #83 — and I agree, you should totally bundle the extensions with the main package. For now, I just manually loaded the vertico-demand code, but it'll be nice to have the process a little more automated in the future. :)

**Comment by minad** [comment] 2021-10-31 21:50
> A vertico-demand feature I'd like to request: a whitelist of commands which automatically enable vertico display.

I would prefer a list where one can configure the UI depending on the completion category, which is more general than the command name. Embark uses the category to add its actions and Marginalia to add its annotations.

**Comment by gcv** [comment] 2021-11-01 01:22
I’m not familiar with completion categories. Is every interactive command guaranteed to be classifiable in this manner? It seems to me that at least a fallback to command name would improve flexibility.

**Comment by minad** [comment] 2021-11-01 10:38
> I’m not familiar with completion categories. Is every interactive command guaranteed to be classifiable in this manner? It seems to me that at least a fallback to command name would improve flexibility.

It is possible to add a completion category to every command via Marginalia. However you are right that having a command filter would improve flexibility.

There are two more things I dislike about the current state of vertico-demand and that's why I haven't merged it yet.

1. I miss an indicator which shows how many candidates match. Given such an indicator the user could tell if RET/TAB will indeed finish completion.
2. There is a mismatch in behavior with regards to how input is treated if REQUIRE-MATCH=nil. In vertico the first candidate is selected instead of the prompt. Pressing RET will submit the topmost candidate. In contrast in vertico-demand, RET submits the current input. This matters for example for `switch-to-buffer`, where a new buffer is created. I think this is the wrong default - I usually don't want to submit the input string and create a new buffer.

**Comment by minad** [comment] 2021-11-16 16:50
The point that I am making is that Vertico (if activated) deviates a bit from the default UI in how it performs completion. Vertico submits the currently selected candidate and the prompt is only submitted if it is explicitly selected. With default completion it is just the other way round, and I don't like that vertico-demand changes the completion behavior during the completion session.

Example with Vertico+Orderless enabled:

1. C-x b
2. scr RET
3. Takes you to the scratch buffer.

Example with default-completion + Orderless:

1. C-x b
2. scr RET
3. Creates new buffer "scr".

**Comment by gcv** [comment] 2021-11-16 18:35
Okay, so I did understand correctly. Stock Emacs and Vertico do different things. I get that you dislike the change in completion behavior in the context of the same command, depending on whether Vertico has been activated using vertico-demand or not. Counter-argument: most of the time, I just want stock Emacs behavior. Years of muscle memory. But when I opt into using Vertico, I actually want Vertico behavior. The context switch from activating Vertico is entirely obvious, and I can’t imagine making a mistake here.

I think that letting stock Emacs be stock Emacs and letting Vertico be Vertico is a feature here, not a bug.

Anyway, thanks for your work!

**Comment by minad** [comment] 2021-11-16 18:49
> Okay, so I did understand correctly. Stock Emacs and Vertico do
> different things. I get that you dislike the change in completion
> behavior in the context of the same command, depending on whether
> Vertico has been activated using vertico-demand or not.
> Counter-argument: most of the time, I just want stock Emacs behavior.
> Years of muscle memory. But when I opt into using Vertico, I actually
> want Vertico behavior. The context switch from activating Vertico is
> entirely obvious, and I can’t imagine making a mistake here.
> 
> I think that letting stock Emacs be stock Emacs and letting Vertico be
> Vertico is a feature here, not a bug.

Did you try @protesilaos mct? Maybe this fits you better, since it
preserves the default completion behavior entirely but still provides an
enhanced completion display.

I don't want to mix both styles of completion in Vertico and distribute
a vertico-demand extension which has these rough edges, with the change
in behavior. However I think one can avoid the change in behavior and
obtain something which behaves still close to default completion as long
as Vertico is not visible.

I fiddled quite a bit recently on completion packages, in particular my
Corfu package. So I am currently a bit oversaturated regarding
completion but I may look into this again in a while.

**Comment by gcv** [comment] 2021-11-19 14:41
I have a question about the implementation of vertico-demand, if you don't mind. I noticed that `vertico-demand-map` does not define a binding for `[return]`, only `[C-return]`. This means that typing in a new (non-existent) file name after calling `(read-file-name "Select a file: ")` requires hitting <kbd>C-return</kbd> rather than just <kbd>return</kbd> _unless_ Vertico has been fully activated.

It seems like I'm missing something, so could you explain why
```
(define-key vertico-on-demand-map [return] nil)
```
isn't included?

Thanks!

**Comment by minad** [comment] 2021-11-20 20:12
@gcv I just saw that @protesilaos released 0.3.0 of his mct library which also works on Emacs 27 and it works great. I added it myself to my config - I keep multiple completion systems around for testing purposes and switch between them occasionally.

~~~ elisp
;;;###autoload
(defun +completion-ui ()
  (interactive)
  (let ((choice (read-multiple-choice "Select completion UI"
                                      '((?v "vertico" nil vertico-mode)
                                        (?s "selectrum" nil selectrum-mode)
                                        (?m "mct" nil mct-mode)
                                        (?i "icomplete" nil icomplete-mode)
                                        (?f "fido" nil fido-mode)
                                        (?l "icomplete-vertical" nil (lambda ()
                                                                       (icomplete-vertical-mode)
                                                                       (icomplete-mode)))
                                        (?d "default" nil ignore)))))
    (dolist (mode '(vertico-mode selectrum-mode mct-mode fido-mode icomplete-mode icomplete-vertical-mode))
      (when (fboundp mode)
        (funcall mode -1)))
    (funcall (cadddr choice))
    (message "%s enabled" (cadr choice))))
~~~

So please give it a try and let me know what you think about mct. Regarding your question I don't recall why I bound the keys as I did - I probably tried to harmonize the behavior in some way (and failed?). Anyways I will probably rework the vertico-demand extension if I find time for it, such that I am more satisfied with it.

**Comment by gcv** [comment] 2021-11-21 16:00
@minad: I tried mct. It's certainly very very clever, but I ran into a few problems with Emacs 27. `one-column` display does not seem to work, and selecting the first candidate is wonky (though I haven't quite isolated why). Restricting the height of the candidate list buffer window does not seem to be supported, and `temp-buffer-resize-mode` didn't work on my first attempt (and I didn't try harder). I don't have time to experiment with 28 right now to see if it works better.

While there's an argument for making mct or similar behavior the Emacs default, the `*Completions*` buffer is fundamentally too clunky for something as basic as completion, and mct can only papers over its problems.

It seems to me, after trying everything else, that Vertico is the most promising completion system available right now. It just needs clean opt-in and opt-out semantics. Your `vertico-demand` code is close, and works well for me. Don't take this as pressure to work on it further. I have already adapted it for my personal setup and don't really care if you merge it in. (Though I guess I'll have to revisit it if the internal Vertico APIs it uses change in the future.)

Thanks again for your work!

PS: I can't help noticing that you don't include Helm in your `+my-completions` switcher. 🙃

**Comment by minad** [comment] 2021-11-21 16:26
> I tried mct. It's certainly very very clever, but I ran into a few problems with Emacs 27. 

Indeed, it is.

> one-column display does not seem to work, and selecting the first candidate is wonky (though I haven't quite isolated why).

This is expected since Emacs 27 does not support that yet unfortunately.

> Restricting the height of the candidate list buffer window does not seem to be supported, and temp-buffer-resize-mode didn't work on my first attempt (and I didn't try harder). 

This should be fixable by adjusting the display-buffer-alists.

> I don't have time to experiment with 28 right now to see if it works better.

I assume that it works better on Emacs 28, since Prot is targeting Emacs 28 mainly. Also Emacs 28 includes some other improvements I had contributed, e.g., the support for grouping/group-function. I don't want to talk you into using one or the other system, use which fits you best and which works given your current setup.

> While there's an argument for making mct or similar behavior the Emacs default, the *Completions* buffer is fundamentally too clunky for something as basic as completion, and mct can only paper over its problems.

Which problems do you see specifically? 

> It seems to me, after trying everything else, that Vertico is the most promising completion system available right now.

I see it like this - Vertico and Mct approach the problem in slightly different ways. In Mct you always have the minibuffer in its pristine form for *completion*, the input you will submit is the string which is present in the minibuffer as long as you don't move your cursor over to the Completions buffer for *selection*. In Vertico the completion/selection process is more muddied - it leads to a slightly faster selection process. The speed is further improved by the performance optimizations of Vertico (faster and better sorting algorithm, faster grouping algorithm, ...). The Vertico/Selectrum/Ivy UIs work similarly and one could say that these UIs deviate a bit more from how the minibuffer completion has been initially envisioned, while Mct stays closer to this concept. Furthermore Mct retains the advantages of a buffer (You can use Isearch or Avy there for example) at the cost of performance, since all candidates are displayed. On the other hand Vertico/Selectrum/Ivy are slightly snappier and may feel a bit easier to use for beginners which come from other systems. Vertico/Selectrum/Ivy are rather like widgets specifically tailored for the problem at hand, while Mct feels more Emacsy if you will, since it stays close to basic concepts like buffers. However this is of course a subjective interpretation, Emacs has moved into the direction of richer UIs for some time - menu bar, tool bar, transient, etc.

> Your vertico-demand code is close, and works well for me. Don't take this as pressure to work on it further. 

I will work on this further, since it is an interesting idea. When I initially played around with Mct and vertico-demand I liked the unobtrusiveness of the window not popping of right away. I am just not making promises on when this is going to happen :)

> I have already adapted it for my personal setup and don't really care if you merge it in. (Though I guess I'll have to revisit it if the internal Vertico APIs it uses change in the future.)

I would appreciate if you publish it somewhere such that I could merge back improvements. Do you have the FSF copyright assignment?

> PS: I can't help noticing that you don't include Helm in your +completion-hi switcher.

Yes, I don't use Helm or Ivy. I only install them temporarily and rarely for experimentation. Helm and Ivy don't fit the spirit of decoupled and focused packages. They also do not work with my Consult package. Marginalia, Orderless and Embark work at least with Ivy, but I've not heard of Helm support.

**Comment by gcv** [comment] 2021-11-22 22:48
Your discussion about the differences in approach between mct and the minibuffer frameworks reminds me of the Helm documentation: "There are several alternatives to Helm nowaday, they are all providing incremental completion but they lack all the Helm features due to their wrong implementation abusing minibuffer [sic]" (https://emacs-helm.github.io/helm/, Alternatives section).

There's a fair point made here, but I dislike the `*Completions*` buffer. I have used Emacs since the mid-90s, and have hated every time the broken thing popped up. It commits the sin of messing with window layout (this has improved in the last 10 years of Emacs releases but has not been fully fixed since it's easy to get in a state in which it stays on-screen), which I have ranted about (https://github.com/nex3/perspective-el#some-musings-on-emacs-window-layouts). It's the wrong solution to the problem of "I need autocompletion and I need it right now". Not even once have I had the desire to treat my completion candidate list as a buffer I can do buffer-like things on (isearch? no. copy-paste? no.). Having to switch buffers to do completion tasks while trying to do completion is a switch in focus that I never want.

I respect the attempt mct makes to deal with this, but it feels like lipstick on a pig. There already is a non-minibuffer based completion framework, Helm. I get that a lot of people think it's too much or it has bad UI/UX (and agree to some extent), but it's a pretty remarkable piece of software and handles windows and buffers fairly cleanly — which the Emacs stock completion system does not.

You mentioned performance. Completion speed matters a lot. I used Helm for years, and at some point, it started getting sluggish. That's the main reason why I started experimenting with Ivy, Selectrum, and now Vertico.

And, as long as I'm making changes to my setup, I might as well try to make another step towards the ideal completion UI and UX. For me, that's defined as: (1) staying out of the way unless I want it, and (2) minimally disturbing window layout. Pretty much nothing does the former, except vertico-demand. In the past, I implemented all kinds of minor modes which selectively enable Selectrum specifically for certain commands when I know I'll want completion help. The latter can be accomplished using single-window Helm, and I have it kinda working with Vertico (again, selectively), using mini-frame or posframe (basically, I have special advice which enables mini-frame for a handful of commands).

(BTW, none of this is a call to action or a request for anything. I'm just sharing my thoughts.)

**Comment by minad** [comment] 2021-11-22 23:20
> Your discussion about the differences in approach between mct and the minibuffer frameworks reminds me of the Helm documentation: "There are several alternatives to Helm nowaday, they are all providing incremental completion but they lack all the Helm features due to their wrong implementation abusing minibuffer [sic]" (https://emacs-helm.github.io/helm/, Alternatives section).

I just tried Helm again. It seems to disallow movement to the Helm buffer (and jumping around there), so Helm is much more related to Vertico/Ivy/Selectrum where the buffer itself is not supposed to be interacted with directly. Helm is precisely equivalent to the vertico-buffer extension. So if you dislike that the minibuffer is resized and "abused", you can use this. Then a normal buffer is used for the display, but the buffer itself is still not fully functional as in the case of `*Completions*`. This was my argument and this is what distinguishes completion systems like Ivy/Helm/Vertico/Selectrum from Mct/default completion. Needless to say, I disagree with what the Helm maintainer wrote in the Helm documentation. From my perspective Embark+Orderless+Vertico+Marginalia+Consult should result in feature parity. But this shows how large Helm actually is - if we need a multitude of decoupled packages to reproduce a similar feature set. I should note that the goal is not to make a Helm clone, the idea was rather to have something composable - a user may only want to use a subset of the packages and features.

> I respect the attempt mct makes to deal with this, but it feels like lipstick on a pig. There already is a non-minibuffer based completion framework, Helm. I get that a lot of people think it's too much or it has bad UI/UX (and agree to some extent), but it's a pretty remarkable piece of software and handles windows and buffers fairly cleanly — which the Emacs stock completion system does not.

As I wrote above, this is not the case. Helm is different and belongs still to the same class of UIs like Ivy etc. Please don't post shallow dismissals of the work of others here. Protesilaos told me that Mct also has the goal of showing alternatives to the Emacs core developers. It makes the deficiencies of the default completion much more obvious, while still being very close to the original implementation. It may not fit your ideal and this is okay. We have plenty of alternatives now. Furthermore note that many of the facilities provided by the default completion UI are reused by Vertico, in particular the completion styles and the internal completion table machinery. So if one complains about the default completion UI, it is only the top most layer. Hopefully we will see a bit of an untangling of the Emacs completion components in the future: 1. completion styles, 2. minibuffer-complete-* commands and default completions UI.

> You mentioned performance. Completion speed matters a lot. I used Helm for years, and at some point, it started getting sluggish. That's the main reason why I started experimenting with Ivy, Selectrum, and now Vertico.

Performance has been a priority from the start. So no wonder we are can do better than other systems. But on the other hand if you only pop up the completion buffer rarely or after the set of candidates has been filtered heavily, the performance is much less relevant. For a large number of candidates, performance is mostly dominated by sorting. Displaying the candidates is also expensive (probably most expensive), therefore Vertico only shows a subset. For the default UI, all available candidates are shown. This is a necessity since this allows you to interact with the buffer (Isearch/Avy etc). If this is needed is a different question. Many people like this, since it results in a coherent experience across whole Emacs. From my personal experience, I don't need a buffer in most cases. I am happy with a dedicated UI like Vertico - if I want a buffer it is an `embark-collect-snapshot` away.

> And, as long as I'm making changes to my setup, I might as well try to make another step towards the ideal completion UI and UX. For me, that's defined as: (1) staying out of the way unless I want it, and (2) minimally disturbing window layout. Pretty much nothing does the former, except vertico-demand. In the past, I implemented all kinds of minor modes which selectively enable Selectrum specifically for certain commands when I know I'll want completion help. The latter can be accomplished using single-window Helm, and I have it kinda working with Vertico (again, selectively), using mini-frame or posframe (basically, I have special advice which enables mini-frame for a handful of commands).

vertico-demand+vertico-buffer could also be an alternative. You have to configure the display action properly. Also mct fits these requirements. From your requirements I don't see why you would prefer Vertico over Mct, something is missing. Maybe performance is an argument - but performance does not matter if you display the completions on demand, since then there will be a much smaller subset.

Regarding mini-frame/posframe on the other hand I am highly critical. I only use only a single child frame package, my [Corfu](https://github.com/minad/corfu) completion at point UI. Child frames are brittle and prone to flicker (at least on my setup), so I stay away from them. For completion-at-point I like it, but not for minibuffer completion.

**Comment by gcv** [comment] 2021-11-23 01:21
If you think anything I wrote constitutes “shallow dismissals of the work of others”, we have a regrettable communication mismatch. I repeatedly acknowledged the accomplishments of mct and its author. Also, at no point did I imply that I dislike what the author of Helm referred to as minibuffer abuse. My appreciation for Vertico should speak for itself here.

**Comment by minad** [comment] 2021-11-23 01:37
> I have used Emacs since the mid-90s, and have hated every time the broken thing popped up. It commits the sin of messing with window layout (this has improved in the last 10 years of Emacs releases but has not been fully fixed since it's easy to get in a state in which it stays on-screen), which I have ranted about (https://github.com/nex3/perspective-el#some-musings-on-emacs-window-layouts).

> I respect the attempt mct makes to deal with this, but it feels like lipstick on a pig.

This is certainly not a friendly or constructive criticism. I am kind of sensitive about language right now. I am sure you didn't mean it in a bad way, since you acknowledged the accomplishments. Anyways - I assume everything which has to be said has been said here. The discussion can be continued when we come up with new ideas. I am sure I will come back to this issue, since it is interesting to see if Vertico can be less obtrusive.

**Comment by minad** [comment] 2021-12-27 16:44
@gcv I recently added the [vertico-multiform](https://github.com/minad/vertico/#configure-vertico-per-command-or-completion-category) extension. This feature allows us to enable extensions like `vertico-demand`, `vertico-grid` or `vertico-buffer` only for certain commands. `vertico-demand` does not yet exist but having a generic configuration facility is a step in the right direction since it allows us to leverage the enhancements of all these extensions without having to modify the default behavior.

**Comment by gcv** [comment] 2021-12-30 04:45
@minad: I tried vertico-multiform, and it looks really really good. I'm very excited to see all this flexibility added to Vertico — it's getting really close to fully replacing my hodgepodge of completion frameworks and hacked-up advice. Looking forward to what you do next.

While most things I tried work, I have some feedback based on my experiments with these extensions. I'll write it up here, but let me know if you want me to open separate tickets for these.

1. `(setq vertico-buffer-display-action '(display-buffer-same-window))` does not do what I think it should. I expect it to take over the current window, but it seems to do a split anyway. If there's an existing vertical split, the completion buffer splits the other window. I understand that taking over the current window messes with buffer previews, but previews can just be automatically disabled in that case. (I keep previews off because they interfere with [Perspective](https://github.com/nex3/perspective-el) by potentially pulling in buffers I don't want into the current perspective.)
2. I think `vertico-multiform-command-modes` should accept regexes along with symbols. I understand that you prefer category-based configuration, but a lot of packages don't provide command categories, and it's nice and easy to just give a regex to catch all commands in a particular package.
3. `vertico-flat-mode` should (optionally?) support left-right arrow keys to switch candidates instead of (or along with) up-down. That's how ido-mode works, and it's intuitive considering the layout.

**Comment by minad** [comment] 2021-12-30 06:22
Thank you for the feedback! These are good and valid points.

1. I've also observed this and even documented it in the readme. I think this is an issue of `display-buffer-same-window`, it does not work since we create the window from the minibuffer. There are two solutions: Either write your own display function (see https://github.com/minad/vertico/#configure-vertico-per-command-or-completion-category, display-buffer-in-selected) or I temporarily select the original window when displaying the new buffer. I will try the second approach, if it is not satisfactory a custom display action will be the way to go.

2. Agree. I also considered this but left it out for simplicity for now. In my Corfu package and also in Consult I already have such code which accepts both regexps and symbols. I will add this.

3. Mhm. I see your point. vertico-grid-mode also remaps the keys and it is more important there. However vertico-grid-mode does this in a bad way which also affects recursive minibuffes by modifying the original keymap. I will fix this in both grid and flat.

**Comment by gcv** [comment] 2021-12-30 15:56
That was quick! Cool. Thank you.

I just tried `display-buffer-same-window` and the regexp `vertico-multiform-command-modes` settings. Both work great.

The flat and grid keymap changes mostly work, but have some edge cases. I'm playing with this configuration:

```
(setq vertico-multiform-category-modes
      '((file grid)
        (buffer flat)
        (consult-grep buffer)))
```

If I run `switch-to-buffer` (flat mode) and use the right arrow key repeatedly, the following happens:
`{buf1 | buf2 | buf3 | buf4}` changes to `{buf2 | buf3 | buf4}` and then to `{buf3 | buf4}` and `{buf4}`. The left arrow key then puts back `buf3`, `buf2`, and so on. Setting `vertico-cycle` to `t` fixes it. Maybe flat mode should force `vertico-cycle` to `t`?

Arrow keys don't work in grid or flat mode to edit the input string. I tried `find-file` and `switch-to-buffer`. `C-f` and `C-b` do work to edit the string. That might be fine (and maybe inherent to changing the keymap?), but is inconsistent with regular Vertico behavior.

Finally, I added a key binding to toggle grid mode, like this: `(define-key vertico-map (kbd "C-c g") #'vertico-grid-mode)`. Then I ran `execute-extended-command` and turned on the grid using the key binding. Using the right arrow errors out with `End of buffer`. But if I then `C-g` out and use <kbd>M-x</kbd> again, it works. If I then toggle grid mode off, then the right arrow key starts jumping through the list, as if the grid were still active.

**Comment by minad** [comment] 2021-12-30 16:26
Thank you for giving it a test.

> If I run |switch-to-buffer| (flat mode) and use the right arrow key
> repeatedly, the following happens:
> |{buf1 | buf2 | buf3 | buf4}| changes to |{buf2 | buf3 | buf4}| and then
> to |{buf3 | buf4}| and |{buf4}|. The left arrow key then puts back
> |buf3|, |buf2|, and so on. Setting |vertico-cycle| to |t| fixes it.
> Maybe flat mode should force |vertico-cycle| to |t|?

No, this is intentional. Both settings make sense. You can easily set
vertico-cycle in a vertico-flat-mode hook or use
vertico-multiform-command-settings. I try to avoid making too many
independent changes. This is better left to the user.

> Arrow keys don't work in grid or flat mode to edit the input string. I
> tried |find-file| and |switch-to-buffer|. |C-f| and |C-b| do work to
> edit the string. That might be fine (and maybe inherent to changing the
> keymap?), but is inconsistent with regular Vertico behavior.

Yes, it is inconsistent but works reasonably well by default. How should
it work alternatively? We overwrite the navigation keys to move between
the candidates. You could additionally bind other keys
(C-<left>/<right>) in vertico-grid/flat-map which move left and right. I
would also say that tweaking this setting is left to the user.

> Finally, I added a key binding to toggle grid mode, like this:
> |(define-key vertico-map (kbd "C-c g") #'vertico-grid-mode)|. Then I ran
> |execute-extended-command| and turned on the grid using the key binding.
> Using the right arrow errors out with |End of buffer|. But if I then
> |C-g| out and use M-x again, it works. If I then toggle grid mode off,
> then the right arrow key starts jumping through the list, as if the grid
> were still active.

Oh right. This is an issue. The new keymap setup does not work anymore
with toggling. I have to figure out a better way to handle the keymap setup.

**Comment by minad** [comment] 2021-12-30 18:21
I fixed the keymap toggling issue in https://github.com/minad/vertico/commit/10e8508f58ac14c1d9c647cc6c0fbb170cc4afd5.

**Comment by gcv** [comment] 2021-12-31 00:09
The keymap fix works. Nice!

About the other two matters: I get it and your points make sense. Still, vertico-flat display is odd enough IMO that it warrants a mention in the README that `vertico-cycle` is a useful setting through `vertico-multiform-category-settings`.

**Comment by minad** [comment] 2021-12-31 00:14
> About the other two matters: I get it and your points make sense. Still, vertico-flat display is odd enough IMO that it warrants a mention in the README that vertico-cycle is a useful setting through vertico-multiform-category-settings.

Sure, PR welcome :) One could also mention vertico-cycle in the commentary of vertico-flat.el.

**Comment by gcv** [comment] 2021-12-31 08:19
Documentation PR: #169.

**Comment by minad** [comment] 2022-01-02 15:27
Closing. The discussion continued in #168.

**Closed by minad** 2022-01-02 15:27 UTC
Labels: discussion

**Comment by dalgong** [comment] 2022-10-24 03:41
@minad vertico 0.28 seems to not have vertico-demand.el in it. Any reason for it?package?

**Comment by minad** [comment] 2022-10-24 15:08
There exists vertico-unobtrusive-mode as alternative.

**Comment by dalgong** [comment] 2022-10-24 15:10
> There exists vertico-unobtrusive-mode as alternative.

Thanks. I know;) I was just curious why vertico-demand is in the repo but not in the package...
