### ISSUE TITLE
`M-x find-library` contains `./` and `../` multiple times when using vertico

### ISSUE THREAD

**Issue by mohkale** [minad/vertico#80] opened 2021-07-12 16:57 UTC
Okay this is a really weird bug, but I've managed to reproduce with just `emacs -q` and vertico so I have to imagine it's related to vertico.

![Screenshot_20210712_175234](https://user-images.githubusercontent.com/23294780/125326479-023b9680-e33a-11eb-8d60-9e8d3b338843.png)

# Reproduction Instructions
1. Run `emacs -Q`.
2. `M-x package-install vertico`
3. `M-x vertico-mode`
4. `M-x find-library`

## Expected
Shows the list of required libraries.

## Actual
Shows the list of required libraries **AND** `./` and `../` several times.

# Version Information
+ Emacs: `GNU Emacs 28.0.50 (build 3, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4) of 2021-05-24`
+ Vertioc: 0.12

## Notes
Also worth noting this doesn't happen with selectrum. I imagine vertico might be fiddling with `locate-file-completion-table` or something it depends on leading to this behaviour.

**Comment by minad** [comment] 2021-07-12 17:04
Duplicate of #69

**Closed by minad** 2021-07-12 17:04 UTC

**Comment by mohkale** [comment] 2021-07-12 17:18
@minad 

Oooh, I didn't notice #69, sorry.
But the issue here isn't really duplicates but the fact that `./` and `../` are candidates at all. They shouldn't be (I think).

**Comment by minad** [comment] 2021-07-12 18:04
> But the issue here isn't really duplicates but the fact that ./ and ../ are candidates at all. They shouldn't be (I think).

What about reporting this upstream, including the issue about the duplicates? Imo no duplicates and no nonsense candidates should be generated. It is not the job of the UI to fix these backend issues.

**Comment by mohkale** [comment] 2021-07-12 18:09
@minad 

Sounds okay to me but I'm not really sure whether the issue is with up-stream or with vertico. That is to say because it only happens when using vertico I thought it was caused by vertico. Once I have a grasp on the reasoning I'd be more than happy to send a mail to emacs-devel but atm I imagine I'd just get cycled from there to here and vice-versa because I don't really understand whats causing this.

I'll try to debug when I get a chance and when I understand it I'll send a issue.

**Comment by minad** [comment] 2021-07-12 18:47
The issue is that the completion table generate duplicate candidates, see #69. Vertico does not filter them out. Vertico could of course do this filtering, but I believe that tables should ideally not generate duplicate candidates. This is unnecessarily pushing work from the backend to the frontend, slowing everything down.

**Comment by mohkale** [comment] 2021-07-12 18:53
@minad 

Okay, just tried with icomplete and the issues still there (although icomplete seems to strip out the duplicates). Looks to be only an issue with `completing-read` compatible frontend. Regardless I'll open a bug-report on emacs-devel mailing list soon.

**Comment by minad** [comment] 2021-07-12 19:22
What do you mean regarding `completing-read` compatible frontends? It affects all frontends - they all get the duplicates if asking the backend (completion table) for completions and may or may not filter out the candidates.

**Comment by mohkale** [comment] 2021-07-12 19:26
@minad

> What do you mean regarding completing-read compatible frontends? It affects all frontends - they all get the duplicates if asking the backend (completion table) for completions and may or may not filter out the candidates.

Well I meant selectrum doesn't have it and selectrum isn't completing-read compatible. I just tried with ivy and ivy does have the issue. In this case I think selectrum is the outlier and as you state all backends have the same issue. Apologies for any confusion :sweat:.

**Comment by minad** [comment] 2021-07-12 19:39
Selectrum also has an issue with duplicates in general. Selectrum has another quirk - it replaces the read-library-function with its own version for some reason which is unclear to me. I guess it removes the duplicates there. If you want to really check this, try the following:

~~~ elisp
(completing-read "Prompt: " '("duplicate" "duplicate" "duplicate" "duplicate"))
~~~

It would be very helpful to check what the UIs with that. I guess most do not filter out the duplicates except default completion and Icomplete, which also uses `completion-all-sorted-completions`. In this function the duplicate removal happens. Furthermore `completion-insert-string` filters out consecutive duplicates, when inserting the strings in the default UI. This removal there also doesn't make sense to me. There is a duplicate duplicate removal it seems to me.
