### ISSUE TITLE
Emacs 29, problem with `M-x M-X...`

### ISSUE THREAD

**Issue by maxbrieiev** [minad/vertico#252] opened 2022-07-22 08:34 UTC
In a recent Emacs change, pressing `M-X` after `M-x` or `M-X` will toggle completion mode.
See commit cdbb02a597298b7812b456fca3d61e223dc40b7c

This seems to not work well with vertico.

1. emacs -Q

2.  `M-x M-X`
This will toggle from `execute-extended-command` to `execute-extended-command-for-buffer`. Pressing `M-X` again will switch back to the `execute-extended-command`.
Note this doesn't recurse into new recursive level.

3. `C-g`
  Exit minibuffer session

Now let's enable vertico.

4. `M-x package-initialize RET`
5. `M-x vertico-mode RET`

6. `M-x M-X`
Now, with vertico mode enabled this will complain: "Command attempted to use minibuffer while in minibuffer".
And if the variable `enable-recursive-minibuffers` was set, this would start a new recursive minibuffer (instead of toggling the command). Now you need to press C-g repeatedly to exit each recursive level. Additionally this somehow messes completion candidates, so that many of them are wrong.

**Comment by minad** [comment] 2022-07-22 10:51
I close this since I don't support Emacs 29 yet. It may as well be that this command has to be changed again upstream for better compliance with completion UIs. In the meantime could you please check if icomplete-mode and icomplete-vertical-mode work with M-x M-X? If M-x M-X was well implemented it would work out of the box with vertico/icomplete etc. As I see it, the command should be implemented such that it just replaced the minibuffer-completion-predicate instead of messing with recursive minibuffers.

**Closed by minad** 2022-07-22 10:51 UTC

**Comment by maxbrieiev** [comment] 2022-07-22 11:16
I checked it with icomplete and icomplete vertical and both of them seem to work with no issues.

**Comment by minad** [comment] 2022-07-22 11:51
I took another look. The issue is just a minor key binding problem. M-X is bound in the  minibuffer-local-must-match-map. This keymap is not used by Vertico. You could try binding the relevant commands in the vertico-map. We could reconsider using the minibuffer-local-must-match-map in Vertico but these maps are very cluttered already.

**Comment by maxbrieiev** [comment] 2022-07-22 12:28
You are right. Binding M-X in vertico-map to execute-extended-command-cycle solves the issue.

**Comment by minad** [comment] 2022-07-22 12:37
But from what I can tell the implementation seems kind of broken. If I execute M-X in an arbitrary command which requires matches it will throw a signal which is then not caught. The proper way to implement this would be to only bind M-X in an additional local map installed by M-x.

**Comment by minad** [comment] 2022-07-22 12:37
See here: https://github.com/emacs-mirror/emacs/blob/82116a5ea382cf87138d8cde3e7d770e540a7d26/lisp/minibuffer.el#L2763

**Comment by maxbrieiev** [comment] 2022-07-22 13:20
Ok. So for now it is semi-broken.

On the other hand, it is somewhat similar to other commands that only work properly in certain context.
For example, `consult-history` should only be bound to a key if the proper history list is available, but seems like most people still add it to the global key map.

**Comment by minad** [comment] 2022-07-26 21:37
Should be fixed by https://github.com/emacs-mirror/emacs/commit/015cf7824ea511180329dabcb67c533661da3fff
