### ISSUE TITLE
post-command-hook (vertico--exhibit): (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by rwilson-lib** [minad/vertico#179] opened 2022-01-11 08:49 UTC
Hi
After update vertico package when I press C-h v is get the error msg Error in post-command-hook (vertico--exhibit): (wrong-type-argument stringp nil)

Vertico versions: 0.19
Emacs version: GNU Emacs 28.0.90 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H1519)) of 2021-12-13

**Comment by minad** [comment] 2022-01-11 12:08
I cannot reproduce this. Please provide a stack trace and a minimal recipe based on emacs -Q. In order to obtain a stacktrace evaluate this first:

~~~ elisp
(defun force-debug (func &rest args)
  (condition-case e
      (apply func args)
    ((debug error) (signal (car e) (cdr e)))))

(advice-add #'vertico--exhibit :around #'force-debug)
~~~

**Comment by minad** [comment] 2022-01-11 12:29
See also https://github.com/minad/vertico/issues/27#issuecomment-1008855141. An update of Marginalia may fix this

**Comment by minad** [comment] 2022-01-11 14:48
Should be fixed finally by https://github.com/minad/marginalia/commit/ff93c57d89c08214a6ed57f752ef424a6878ba77. Please confirm.

**Closed by minad** 2022-01-11 14:48 UTC
