### ISSUE TITLE
Optionally enabling annotations for vertico-flat-mode and vertico-grid-mode?

### ISSUE THREAD

**Issue by phikal** [minad/vertico#236] opened 2022-05-22 19:19 UTC
Hi,

I was wondering if there is any reason the `arrange-candidates` functions for `vertico-grid-mode` and `vertcio-flat-mode` do not show annotations, or at least allow for the user to enable them if they decide to want them?

**Comment by minad** [comment] 2022-05-22 21:54
I already commented about this in https://github.com/minad/vertico/issues/153. The idea is that the grid/flat/unobtrusive modes are compressed. We can fit as many candidates as possible and display no auxillary information. For normal Vertico mode or the buffer mode we have plenty of space to display rich and long annotations, e.g., in the style of the Marginalia package. Also the builtin annotations are irregular, some are long, some are short. Annotations are therefore not a good fit for the compressed display modes. Now we could make this configurable but I really do not see a point, it will just look ugly. 

In the case of Marginalia, the tendency was also to use richer and longer annotations. This is not something I had planned initially. I was more interested in a less noisy display. But it turned out that almost everyone wants to activate the rich and long annotations and the noise isn't that of a big problem since the annotations are nicely aligned in columns.

For me personally I am happy without annotations in unobtrusive/flat/grid mode. I miss only a single annotation - the keybindings in M-x for which I use unobtrusive mode. When I want to see metadata I use the multiform mode toggle to switch to the vertical display. On the other hand I could use the marginalia-annotate-binding annotator instead of the verbose marginalia-annotate-command annotator which also shows the first line of the doc string. The binding annotator returns a fairly short string so that would work well even in the compressed display modes.

However it would be much more elegant if the annotation-function/affixation-function of the completion metadata was replaced with a decoration-function which provides more metadata. I imagine this function to return multiple annotation fields for each candidate with additional field metadata (prefix flag, desired length, left/right alignment, short/long flag, ...). If a field is marked as short we could display this field even in the compressed display modes. Furthermore multiple annotation fields could be aligned by the UI directly instead of by a middleware like Marginalia. Ideally the entire formatting/alignment is pushed to the UI.

If you are interested in discussing improvements to the annotation part of the completing-read API we can continue the discussion via email.

**Closed by minad** 2022-05-22 21:54 UTC

**Comment by shtwzrd** [comment] 2022-05-23 12:47
This is also something I would like, primarily for usage with [all-the-icons-completion](https://github.com/iyefrat/all-the-icons-completion).

I like to use `vertico-grid` for `find-file` but I miss having the file type icons. It could be nice if there was some way of enabling specific annotations in flat/grid, or customizing the format of the candidates.

Not a big thing of course, just mentioning another use-case for annotations in a compressed display mode. :)

**Comment by minad** [comment] 2022-05-23 13:02
@shtwzrd Icons sound like a legitimate use case. The problem is that we cannot distinguish such prefix/postfix strings from more verbose annotations. The reason is simply that the annotation API does not provide sufficient metadata. I usually tend to only implement things which are guaranteed to work well. This way I avoid awkward heuristics and things are simpler.

See what I wrote in https://github.com/minad/vertico/issues/236#issuecomment-1133992609 about a potentially improved annotation api decoration-function. It would be nice if the completion API was extended accordingly. I could define my own extension x-decoration-function or vertico-decoration-function, but I am rather conservative regarding extensions. I would prefer an official extension. Otherwise we end up with the same situation as with Company with it's numerous Capf extensions.
