### ISSUE TITLE
Resizing problem

### ISSUE THREAD

**Issue by tumashu** [minad/vertico#13] opened 2021-04-13 02:09 UTC
![IMG_20210413_100542_edit_501759249706248](https://user-images.githubusercontent.com/67725/114486366-51413500-9c40-11eb-8aff-631cd5300a77.jpg)

**Comment by tumashu** [comment] 2021-04-13 02:12
0.3 seem no this problem.

**Comment by minad** [comment] 2021-04-13 03:49
Please tell me your Emacs version (Emacs 28?) and Vertico version (0.4?). The problem may have been introduced by https://github.com/minad/vertico/commit/e58f38062ad8272c3f2d4e8f65ef5a7a2ae0f9c0. @manuel-uberti Do you see this on Emacs 28?

**Comment by tumashu** [comment] 2021-04-13 04:12
I use emacs28 gccemacs,  vertico 0.4

**Comment by minad** [comment] 2021-04-13 04:14
Okay, thanks. Please always report such crucial information. Can you try https://github.com/minad/vertico/commit/e58f38062ad8272c3f2d4e8f65ef5a7a2ae0f9c0 and the version before that in order to confirm that this is the issue.

**Comment by minad** [comment] 2021-04-13 04:17
I will send and Emacs 28 upstream bug report then. There seem to be a few regressions around minibuffer resizing in Emacs 28. See https://github.com/raxod502/selectrum/issues/435.

**Comment by minad** [comment] 2021-04-13 04:19
See also #5

**Comment by manuel-uberti** [comment] 2021-04-13 08:46
Using Emacs 28 (commit `6de79542e4`) and `vertico-0.4.0.20210412.170544`, if I set `resize-mini-windows` to `t` the resizing works as expected.

**Comment by minad** [comment] 2021-04-13 10:30
Okay, I close this issue then. I assume @tumashu's Emacs is broken since there was also another face issue reported in the Consult repository, which seems like an Emacs bug. @tumashu Please report back if issues persist after updating to the newest Emacs28 master branch.

**Closed by minad** 2021-04-13 10:30 UTC
