### ISSUE TITLE
Face attributes from the candidates are still present when they get expanded to the prompt

### ISSUE THREAD

**Issue by joca-bt** [minad/vertico#30] opened 2021-05-13 13:14 UTC
When I'm `M-x find-file` the face attributes from the candidates get applied when the candidate is entered to the prompt.

See the picture below for an example. In the picture in the left side the candidates with `pac` are highlighted. When I press `tab` on the first candidate, the directory gets expanded and the prompt is updated (picture in the right side). The highlighting is propagated to the prompt. Is this expected? If so, can we add an option to disable this behaviour and have the prompt just have its regular face?

<img width="680" alt="vertico" src="https://user-images.githubusercontent.com/1297942/118129925-1546ee80-b3fd-11eb-8258-b3f6becc4eb7.png">

**Comment by minad** [comment] 2021-05-13 13:41
I was aware of this problem. The problem is actually a hack in Emacs which should be fixed in Emacs itself. For now I added a workaround.

**Closed** 2021-05-13 13:40 UTC
