### ISSUE TITLE
vertico 0.25 or higher has a problem when creating new files and directories.

### ISSUE THREAD

**Issue by yorisilo** [minad/vertico#276] opened 2022-09-02 17:22 UTC
## problem
Hello. Thank you for the great package.

vertico 0.25 or newer, opening a new file with C-x C-f (find-file) etc..., I got the following error. but If I specify a file that already exists, error is not displayed.

```
Error in post-command-hook (vertico--exhibit): (wrong-type-argument stringp nil)
```

I don't know why, but if you revert the following to 0.24, the error will no longer occur.
https://github.com/minad/vertico/compare/0.24...0.25#diff-d3020100b4cbfdd2261f81cbfbe3c86b96d3e02d972bff65cc1b86466eb81040R190-R199

``` diff
@@ -184,22 +184,19 @@ See `resize-mini-windows' for documentation."
   (or (and (equal (car vertico--history-hash) vertico--base) (cdr vertico--history-hash))
       (let* ((base vertico--base)
              (base-size (length base))
-             ;; History disabled if `minibuffer-history-variable' eq `t'.
-             (hist (and (not (eq minibuffer-history-variable t))
+             (hist (and (not (eq minibuffer-history-variable t)) ;; Disabled for `t'.
                         (symbol-value minibuffer-history-variable)))
              (hash (make-hash-table :test #'equal :size (length hist))))
-        (if (= base-size 0)
-            ;; Put history elements into the hash
-            (cl-loop for elem in hist for index from 0 do
-                     (unless (gethash elem hash)
-                       (puthash elem index hash)))
-          ;; Drop base string from history elements, before putting them into the hash
-          (cl-loop for elem in hist for index from 0 do
-                   (when (and (>= (length elem) base-size)
-                              (eq t (compare-strings base 0 base-size elem 0 base-size)))
-                     (setq elem (substring elem base-size))
-                     (unless (gethash elem hash)
-                       (puthash elem index hash)))))
+        (cl-loop for elem in hist for index from 0 do
+                 (when (or (= base-size 0)
+                           (and (>= (length elem) base-size)
+                                (eq t (compare-strings base 0 base-size elem 0 base-size))))
+                   (let ((file-sep (and (eq minibuffer-history-variable 'file-name-history)
+                                        (string-match-p "/" elem base-size))))
+                     ;; Drop base string from history elements & special file handling.
+                     (when (or (> base-size 0) file-sep)
+                       (setq elem (substring elem base-size (and file-sep (1+ file-sep)))))
+                     (unless (gethash elem hash) (puthash elem index hash)))))
         (cdr (setq vertico--history-hash (cons base hash))))))
 
```

## video
https://user-images.githubusercontent.com/10104705/188195956-85235032-4227-46af-99fc-6f4ea7f46286.mov

**Comment by minad** [comment] 2022-09-03 15:57
Can you please provide a minimal recipe with emacs -Q which demonstrates the issue? The only loaded package should be Vertico.

**Comment by minad** [comment] 2022-09-04 15:48
Closing. I cannot reproduce this issue in my configuration. Please try to reproduce it with a minimal configuration.

**Closed by minad** 2022-09-04 15:48 UTC
