### ISSUE TITLE
[Question] `evil-local-mode` enabled when `vertico-buffer-mode` is on

### ISSUE THREAD

**Issue by condy0919** [minad/vertico#171] opened 2022-01-03 11:31 UTC
It can be reproducible via the following recipe.

``` emacs-lisp
;; emacs -Q -l /path/to/this/recipe.el
;;
;; Fix the package version
(add-to-list 'load-path (file-name-as-directory "~/.emacs.d/elpa/evil-20211223.1752/"))
(add-to-list 'load-path (file-name-as-directory "~/.emacs.d/elpa/vertico-0.18/"))

(setq evil-want-minibuffer nil)

(require 'vertico)
(require 'vertico-buffer)
(require 'evil)

(evil-mode +1)
(vertico-mode +1)
(vertico-buffer-mode +1)
```

<kbd>C-x C-f</kbd> then <kbd>C-n</kbd>, <kbd>C-n</kbd> will invoke `evil-complete-next` which implies the buffer is evilfied.

Add logs in function `vertico-buffer--setup`,

![image](https://user-images.githubusercontent.com/4024656/147913797-2a4dcd04-0fbf-4ff7-bac3-4197d89bdc77.png)

an odd thing happens. After calling `set-window-buffer`, `evil-local-mode` is on by `evil-initialize`.

According to `evil-initialize`,

```elisp
(defun evil-initialize ()
  "Enable Evil in the current buffer, if appropriate.
To enable Evil globally, do (evil-mode 1)."
  (unless (and (minibufferp) (not evil-want-minibuffer))
    (evil-local-mode 1)
    (evil-initialize-state)))

;;;###autoload (autoload 'evil-mode "evil" nil t)
(define-globalized-minor-mode evil-mode
  evil-local-mode evil-initialize)
```

it only happens if current buffer is not minibuffer or the variable `evil-want-minibuffer` is `t`.

I wonder how it happens, is the buffer's major-mode changed? Since minor-modes run after major-mode-hooks.

**Comment by minad** [comment] 2022-01-03 11:39
`vertico-buffer-mode` displays the minibuffer (`*Minibuf-1*`) in another window, but it is still the normal minibuffer. Actually `vertico-buffer-mode` should rather be called `vertico-window-mode`, since it just uses another window to display the minibuffer. Note that the focus stays in the mini window. Does this explain the issue? Try also `(setq vertico-buffer-hide-prompt nil)` to see what is going on. I am not familiar with the evil specifics.

**Comment by minad** [comment] 2022-01-03 11:54
After rereading your issue - it seems you already looked into the internals of vertico-buffer. The odd thing is that `set-window-buffer` changes the mode. I suggest you trace the function call of `evil-initialize` or `evil-local-mode`. Then the call chain will tell you which hook is turning on evil mode in the minibuffer. Maybe there are some window configuration change hooks in evil?

**Comment by condy0919** [comment] 2022-01-03 11:55
Thanks for your tips.

**Comment by minad** [comment] 2022-01-03 12:14
Another cause could be that evil mode makes heavy use of `permanent-local` buffer variables. I've observed issues before with permanently local variables in Consult+Evil. So maybe there is an Emacs bug here and for some reason Emacs restores permanently local variables when calling `set-window-buffer`.

**Comment by minad** [comment] 2022-01-03 12:18
There are two `window-configuration-change-hooks` in `evil-mode`:

* `evil--jumps-window-configuration-hook`
* `evil-refresh-cursor`

Then there is one `window-scroll-function`:

* `evil-ex-hl-update-highlights-scroll`

These are called by `set-window-buffer` and may cause this.

**Comment by minad** [comment] 2022-01-03 12:42
Since I can reproduce this issue without Vertico, I close the issue here. Please move the issue to the Evil issue tracker.

~~~ elisp
(package-initialize)
(setq evil-want-minibuffer nil)
(require 'evil)
(evil-mode +1)

(defun test-setup ()
  (let* ((temp (generate-new-buffer "*temp*"))
         (win (with-minibuffer-selected-window (display-buffer temp))))
    (message "BEFORE %S" evil-local-mode)
    (set-window-buffer win (current-buffer))
    (message "AFTER %S" evil-local-mode)
    (kill-buffer temp)))

(defun test ()
  (interactive)
  (minibuffer-with-setup-hook #'test-setup
    (read-from-minibuffer "Prompt: ")))
~~~

**Closed by minad** 2022-01-03 12:42 UTC

**Comment by minad** [comment] 2022-01-03 12:46
I identified the bug in evil: https://github.com/emacs-evil/evil/blob/652d726ebd8cdfcac3e97a801721f33b5b832a0a/evil-core.el#L362-L373

**Comment by condy0919** [comment] 2022-01-03 12:47
You're awesome!
