### ISSUE TITLE
M-x error in gccemacs

### ISSUE THREAD

**Issue by yufw** [minad/vertico#41] opened 2021-05-20 13:19 UTC
I've tried vertico today with gccemacs, the completion UI works for find-file, but on M-x, I got '[Error in post-command-hook (vertico--exhibit): (wrong-type-argument stringp nil)]'

**Comment by minad** [comment] 2021-05-20 13:23
Duplicate of #32. Your Emacs is slightly outdated. If you upgrade to newest Emacs master, the issue should be gone. Alternatively stable Emacs 27.1 and 27.2 work.

**Closed by minad** 2021-05-20 13:23 UTC

**Comment by daviwil** [comment] 2021-05-20 17:03
I'm experiencing this issue with Vertico commit 030b964 in Emacs 27.2 on Windows, the same error in minibuffer when I use `M-x`.  I also see it with `consult-find-file` but not `switch-to-buffer`.  Is there anything I can do to help diagnose the issue further?

**Comment by daviwil** [comment] 2021-05-20 17:05
Ahh, I just followed a hint in #32 and disabled Marginalia then re-enabled Vertico and the problem went away.  As soon as I turn Marginalia back on, I start seeing the error again.

**Comment by daviwil** [comment] 2021-05-20 17:10
OK, I was using Vertico from the latest commit but Marginalia from tag 0.5, once I updated Marginalia to the latest commit on the repo the problem was resolved!

**Comment by minad** [comment] 2021-05-20 17:13
@daviwil Sorry for the mess with the versions. This is a big issue with independent components, every component must follow the APIs closely. Generally if everything is on the most recent state and Emacs is stable or a sufficiently recent master it should work :)

**Comment by daviwil** [comment] 2021-05-20 17:15
No worries!  I think it's probably better to track the latest changes in these repos anyway since they're actively developed.  That's what I'll be doing in my straight.el config from now on :)

**Comment by yufw** [comment] 2021-05-23 15:24
@minad Yes, I tried latest master and it works as expected. I was using the latest native-comp branch before, was not aware that it's merged into master.
