### ISSUE TITLE
Notmuch.el select tag error: "Tag must be in the form of +'this_tag' or '-that_tag'"

### ISSUE THREAD

**Issue by mgraham** [minad/vertico#119] opened 2021-09-08 05:33 UTC
In a notmuchmail search buffer you can tag all matching messages using `notmuch-search-tag-all`.

Vertico brings up a list of tags.  If I select `+inbox`, Vertico shows:

```
Tag all (+mod -drop) (1 selected):
------Selected----------
✔ +inbox
------Select multiple----
+new
+sent
+spam
...
```

So far so good.  If I now press `RET`, I get the error message:

```
Tag must be in the form of '+this_tag' or '-that_tag'
```

Is vertico maybe returning the selection in a different format than notmuch.el expects?

I have verified that I can tag messages properly when vertico is globally disabled.  Would it be possible to disable vertico just for this one completion?

**Comment by minad** [comment] 2021-09-08 06:16
@ntatask already reported this issue to Consult, see https://github.com/minad/consult/issues/410. The problem is that notmuch abuse the `completing-read-multiple` API a bit. Hopefully the issue can be fixed in notmuch itself. In the meantime the issue can be fixed by advising `notmuch-read-tag-changes`.

~~~ elisp
(advice-add #'notmuch-read-tag-changes :filter-return (lambda (x) (mapcar #'string-trim x)))
~~~

**Closed by minad** 2021-09-08 06:16 UTC

**Comment by mgraham** [comment] 2021-09-08 06:21
Fantastic - thank you very much @minad !!

**Comment by minad** [comment] 2021-09-18 17:48
cc @iyefrat, you may want to add the workaround to Doom?

**Comment by iyefrat** [comment] 2021-09-20 13:27
Yes, I'll add it to doom if the [bug report](https://yhetil.org/notmuch/86a6k7hd43.fsf@gmail.com/T/#u) seems to take a while to resolve, but with luck I'll just bump `notmuch.el`. Thanks!

**Comment by minad** [comment] 2021-09-20 14:27
@iyefrat Thanks for linking the notmuch bug report here. It is of course better to fix the issue there.
