### ISSUE TITLE
Position of point after inserting long strings in completion minibuffer with `read-answer`

### ISSUE THREAD

**Issue by whxvd** [minad/vertico#385] opened 2023-07-25 18:49 UTC
In a recent Emacs 29 (commit `4e977136d31` from Mon Jul 24 16:22:07 2023 +0200). In `emacs -Q` evaluate the following:

```emacs-lisp
(package-install 'vertico)

(setq short (make-string 5 ?s)
      long  (make-string 500 ?l))

(keymap-set global-map "C-c x s" (lambda () (interactive) (insert short)))
(keymap-set global-map "C-c x l" (lambda () (interactive) (insert long)))
(keymap-set global-map "C-c x x"
            (lambda ()
              (interactive)
              (insert (pcase-exhaustive
                          (read-answer "Question: "
                                       '(("s" ?s "help short")
                                         ("l" ?l "help long")))
                        ("s" short)
                        ("l"  long)))))

(setopt enable-recursive-minibuffers t)
(vertico-mode 1)
```

Then evaluate `(completing-read "CR: " '("a"))`. In the minibuffer type `C-c x x l RET` to insert the long string via `read-answer`. Two unexpected things happen:

1. The point in the minibuffer is at the very beginning, before "CR:". Expected: Point is at the very end.

2. The minibuffer now seems to have `truncate-lines` enables.

Contrast this with:

- When instead inserting the long string via `C-c x l` (i.e., not via `read-answer`), neither (1), nor (2) happens.

- When doing the same experiment with `(completing-read "CR: " nil)` (empty collection), and using either method of inserting the long string, (1) does not happen, but (2) still does.

**Comment by minad** [comment] 2023-07-25 20:10
Thanks for the report. I can only partially reproduce this and the behavior seems mostly as intended.

1. For me the point is at the very end.
2. This is intended. `truncate-lines` should be enabled always and only disabled if point is moved to the right edge of the window. The idea is that the full prompt is always visible.

https://github.com/minad/vertico/blob/d1dd2f74dbcb0817c70e7211fc438b70648a3ee1/vertico.el#L621

However I discovered an issue with scrolling, which I've fixed in https://github.com/minad/vertico/commit/d1dd2f74dbcb0817c70e7211fc438b70648a3ee1.

**Closed as completed by minad** 2023-07-25 20:10 UTC

**Comment by whxvd** [comment] 2023-07-26 13:52
> For me the point is at the very end after the long input as expected. Can you please be more precise about the particular problem, which you observed here?

I cloned https://github.com/minad/vertico and https://github.com/emacs-compat/compat, and updated to the very latest commit from the `emacs-29` branch. (I did not compile Vertico and Compat.)

Then I put the following into a file:

```emacs-lisp
(progn
  (push (file-name-concat (getenv "HOME") "usr" "emacs" "compat") load-path)
  (push (file-name-concat (getenv "HOME") "usr" "emacs" "vertico") load-path)

  (setq short (make-string 5 ?s)
	long  (make-string 500 ?l))

  (keymap-set global-map "C-c x s" (lambda () (interactive) (insert short)))
  (keymap-set global-map "C-c x l" (lambda () (interactive) (insert long)))
  (keymap-set global-map "C-c x x"
	      (lambda ()
		(interactive)
		(insert (pcase-exhaustive
			    (read-answer "Question: "
					 '(("s" ?s "help short")
					   ("l" ?l "help long")))
			  ("s" short)
			  ("l"  long)))))

  (setopt enable-recursive-minibuffers t)
  (require 'vertico)
  (vertico-mode 1)
  (completing-read "CR: " '("a")))
```

Then I started `src/emacs --font Hack:pixelsize=16 --quick` from the Emacs repository (`src/emacs -Q` leads to the same issue, but has a less nice font), opened the file, and hit `C-M-x` followed by `C-x x l RET`. That result is:

![witness](https://github.com/minad/vertico/assets/13905031/bd365218-97ea-43e0-b69f-2efbfeb9c759)

I.e., point is at the beginning of the prompt.

I am on Arch Linux and use Xorg/i3.

**Comment by whxvd** [comment] 2023-07-26 14:53
The following happens only with the current Elpa version of Vertico, and not with the version from the repo, anymore, both when using `C-c x l`, and when using `C-c x x l RET` to insert the long string:

![witness](https://github.com/minad/vertico/assets/13905031/46b16165-3c37-44b6-b04f-23a0614a7443)

**Comment by whxvd** [comment] 2023-07-26 17:54
> But in any case, if you want to prevent point from moving into the prompt you can use the following snippet as documented in the README:
> 
> ```emacs-lisp
>     (setq minibuffer-prompt-properties
>           '(read-only t cursor-intangible t face minibuffer-prompt))
>     (add-hook 'minibuffer-setup-hook #'cursor-intangible-mode)
> ```

I retried with those settings enabled.

> You should probably move point to the end before inserting from the recursive command.

Point already is at the end in that situation. But also doing `C-e` before `C-c x x l RET`, yields:

![witness](https://github.com/minad/vertico/assets/13905031/f7e42308-559c-45d9-8255-4afef79b5a83)

> With these settings I don't see problems.

With these settings, there still is an issue, either with Vertico, or with Emacs. Before reporting here I tested with Vertico disabled. That did not exhibit the problem and left open whether the problem resides in Vertico or in Emacs. With Emacs 28 and Emacs 30, the problem exists, too.

I leave it at that.

**Comment by minad** [comment] 2023-07-26 19:21
To be clear - I see the issue that point ends up at the beginning (but not inside the prompt with the settings given above). This happens not due to insert only, but due to the recursive minibuffer of read-answer. At first, the point is at the end of the minibuffer before and after insertion as it should be, but then it is magically moved to the beginning of the input. This may happen somehow during redisplay or due to minibuffer window restoration. It is not clear how this can be prevented.

**Comment by whxvd** [comment] 2023-07-27 11:58
Thank you for the clarification! Best wishes
